#!/usr/bin/env node

const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const EXPECTED_VERSION = '3.0.72'
const EXPECTED_LABEL = `V${EXPECTED_VERSION}`
const escapedVersion = EXPECTED_VERSION.replaceAll('.', '\\.')

const root = path.resolve(__dirname, '..')
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8')

const releaseNotesPath = path.join(root, 'v2-web', 'src', 'constants', 'releaseNotes.ts')
assert.equal(fs.existsSync(releaseNotesPath), true, 'release notes data file must exist')

const releaseNotes = fs.readFileSync(releaseNotesPath, 'utf8')
assert.match(releaseNotes, new RegExp(`APP_VERSION\\s*=\\s*'${escapedVersion}'`), `APP_VERSION must be ${EXPECTED_VERSION}`)
assert.match(releaseNotes, new RegExp(`version:\\s*'${EXPECTED_LABEL.replaceAll('.', '\\.')}'`), `release notes must include ${EXPECTED_LABEL}`)
assert.match(releaseNotes, /施工缓存一键上传修复/, 'release notes must describe the V3.0.72 construction one-click upload fix in Chinese')
assert.match(releaseNotes, /存在本地缓存即可点击/, 'release notes must state cached upload buttons remain clickable')
assert.match(releaseNotes, /保存稳定的 Blob 数据/, 'release notes must describe cached photo Blob persistence')
assert.match(releaseNotes, /空照片占位不再被误判/, 'release notes must describe empty cached photo guard')
assert.match(releaseNotes, /人工确认条码状态修复/, 'release notes must keep the V3.0.71 manual barcode confirmation fix in Chinese')
assert.match(releaseNotes, /驾驶舱资料组条码准确率/, 'release notes must keep the V3.0.71 project board accuracy cache fix in Chinese')
assert.match(releaseNotes, /通过”和“全部”筛选项/, 'release notes must keep the V3.0.71 passed and all filters in Chinese')
assert.match(releaseNotes, /当前筛选条件下/, 'release notes must describe filtered barcode review search in Chinese')
assert.match(releaseNotes, /数据中台照片加载修复/, 'release notes must describe the V3.0.70 data center photo fix in Chinese')
assert.match(releaseNotes, /删除项目驾驶舱系统状态/, 'release notes must describe the V3.0.70 project board system-status removal in Chinese')
assert.match(releaseNotes, /任务领取完成按钮锁定/, 'release notes must describe the V3.0.68 claim task completed button lock in Chinese')
assert.match(releaseNotes, /主按钮显示“已审阅”并禁用/, 'release notes must describe reviewed action button lock in Chinese')
assert.match(releaseNotes, /施工按钮显示“已施工”并禁用/, 'release notes must describe construction action button lock in Chinese')
assert.match(releaseNotes, /任务领取完成态显示修复/, 'release notes must describe the V3.0.67 claim task completion status fix in Chinese')
assert.match(releaseNotes, /审阅进度达到 100%/, 'release notes must describe review 100 percent shows 已审阅')
assert.match(releaseNotes, /施工进度达到 100%/, 'release notes must describe construction 100 percent shows 已施工')
assert.match(releaseNotes, /审阅与数据中台质量标签/, 'release notes must describe the V3.0.66 review and data center quality labels in Chinese')
assert.match(releaseNotes, /扫码通过X\/3/, 'release notes must describe the group barcode X/3 status in Chinese')
assert.match(releaseNotes, /人工确认/, 'release notes must describe manual confirmation audit in Chinese')
assert.match(releaseNotes, /条码数字 OCR 补全/, 'release notes must keep the V3.0.65 OCR barcode number completion update in Chinese')
assert.match(releaseNotes, /OCR 补全结果不参与自动归档/, 'release notes must keep OCR auto-archive safety text')
assert.match(releaseNotes, /非通过照片慢速重扫/, 'release notes must describe the V3.0.64 slow non-matched rescan update in Chinese')
assert.match(releaseNotes, /审阅页扫码复核/, 'release notes must describe the V3.0.63 review barcode rescan update in Chinese')
assert.match(releaseNotes, /条码识别抗斜拍增强/, 'release notes must describe the V3.0.62 barcode rescue fix in Chinese')
assert.match(releaseNotes, /低成本焦点裁剪/, 'release notes must describe low-cost focus crop in Chinese')
assert.match(releaseNotes, /3130009382030009453489/, 'release notes must include the verified field barcode value')
assert.match(releaseNotes, /资料组照片弹窗修复/, 'release notes must describe the V3.0.61 photo dialog fix in Chinese')
assert.match(releaseNotes, /图片解码校验/, 'release notes must describe image decode verification in Chinese')
assert.match(releaseNotes, /单图大图弹窗/, 'release notes must describe single-image preview in Chinese')
assert.match(releaseNotes, /驾驶舱统计服务器快照/, 'release notes must describe the V3.0.60 project board server snapshot update in Chinese')
assert.match(releaseNotes, /优先读取服务器快照/, 'release notes must state the project board reads the server snapshot first')
assert.match(releaseNotes, /默认每 5 分钟/, 'release notes must describe the scheduled server-side refresh interval')
assert.match(releaseNotes, /项目驾驶舱整体性能优化/, 'release notes must keep the V3.0.59 project board performance fix in Chinese')
assert.match(releaseNotes, /轻量任务接口/, 'release notes must describe the lightweight project board task API in Chinese')
assert.match(releaseNotes, /不触发前台扫码或后台重扫/, 'release notes must state project board performance does not trigger barcode rescans')
assert.match(releaseNotes, /终端明细安装人员聚合修复/, 'release notes must describe the V3.0.57 terminal installer aggregation fix in Chinese')
assert.match(releaseNotes, /页面加载性能优化/, 'release notes must describe the V3.0.58 page performance fix in Chinese')
assert.match(releaseNotes, /优先按资料组照片创建人聚合/, 'release notes must describe photo creator based aggregation in Chinese')
assert.match(releaseNotes, /终端明细安装人员姓名修复/, 'release notes must keep the V3.0.56 terminal installer display name fix in Chinese')
assert.match(releaseNotes, /账号统一转换为账号管理中的姓名/, 'release notes must describe installer account-to-name mapping in Chinese')
assert.match(releaseNotes, /终端明细安装人员完成占比/, 'release notes must keep the V3.0.55 terminal installer completion share update in Chinese')
assert.match(releaseNotes, /安装人员展示新增完成占比/, 'release notes must describe installer completion share in Chinese')
assert.match(releaseNotes, /驾驶舱终端卡片与正式文案整理/, 'release notes must keep the V3.0.54 dashboard terminal card update in Chinese')
assert.match(releaseNotes, /20 条每页/, 'release notes must describe the terminal detail dialog pagination in Chinese')
assert.match(releaseNotes, /删除驾驶舱首屏和终端卡片区域的解释性文字/, 'release notes must describe production copy cleanup in Chinese')
assert.match(releaseNotes, /驾驶舱重复卡与照片弹窗修复/, 'release notes must keep the V3.0.53 dashboard card and photo dialog fix in Chinese')
assert.match(releaseNotes, /数据中台与条码复核清单优化/, 'release notes must describe the V3.0.51 data center update in Chinese')
assert.match(releaseNotes, /每次最多 20 组/, 'release notes must describe slow 20-group barcode slices')
assert.match(releaseNotes, /导出 Excel/, 'release notes must describe barcode review Excel export')
assert.match(releaseNotes, /资料组条码整组识别口径修复/, 'release notes must describe the V3.0.50 group-wide barcode evidence fix in Chinese')
assert.match(releaseNotes, /整组采集条码证据/, 'release notes must describe scanning all four group photos for evidence')
assert.match(releaseNotes, /累计识别到表号、模块号、采集器号三项即判定通过/, 'release notes must state the group barcode pass rule in Chinese')
assert.match(releaseNotes, /照片级图片准确率仍只统计/, 'release notes must state photo accuracy denominator remains category based')
assert.match(releaseNotes, /历史无法识别条码重扫/, 'release notes must describe the V3.0.49 unreadable barcode rescan in Chinese')
assert.match(releaseNotes, /每批 50 组/, 'release notes must describe 50-group unreadable rescan batches')
assert.match(releaseNotes, /重扫批次标记/, 'release notes must describe unreadable recheck batch markers')
assert.match(releaseNotes, /条码维护自动归档稳定性修复/, 'release notes must describe the V3.0.49 barcode maintenance stability fix in Chinese')
assert.match(releaseNotes, /错误明细输出/, 'release notes must describe barcode maintenance error details')
assert.match(releaseNotes, /条码后台维护与自动归档/, 'release notes must describe the V3.0.49 barcode maintenance update in Chinese')
assert.match(releaseNotes, /每天 00:00/, 'release notes must describe the daily midnight maintenance timer')
assert.match(releaseNotes, /自动归档/, 'release notes must describe barcode passed auto archive')
assert.match(releaseNotes, /资料组条码完整照片口径加固/, 'release notes must keep the V3.0.45 complete photo set barcode rule in Chinese')
assert.match(releaseNotes, /4 张有效照片完整/, 'release notes must state that only complete four-photo groups are checked')
assert.match(releaseNotes, /不计入准确率分母/, 'release notes must state incomplete groups are excluded from the denominator')
assert.match(releaseNotes, /后台静默条码重算/, 'release notes must keep the V3.0.43 backend barcode recompute note in Chinese')
assert.match(releaseNotes, /前台页面只读取后端结果/, 'release notes must state frontend only reads backend barcode results')
assert.match(releaseNotes, /资料组条码长表号累计识别修复/, 'release notes must describe the V3.0.42 long meter barcode fix in Chinese')
assert.match(releaseNotes, /长扫码规则/, 'release notes must mention long scan matching in Chinese')
assert.match(releaseNotes, /待派发异常历史模块误报清理/, 'release notes must describe the V3.0.39 exception dispatch cleanup in Chinese')
assert.match(releaseNotes, /缺少模块资产编号/, 'release notes must describe stale missing module note cleanup')
assert.match(releaseNotes, /PostgreSQL/, 'release notes must mention PostgreSQL cleanup scope')
assert.match(releaseNotes, /version:\s*'V3\.0\.38'/, 'release notes must include V3.0.38')
assert.match(releaseNotes, /施工采集 00000000 工单修复/, 'release notes must describe the construction 00000000 fix in Chinese')
assert.match(releaseNotes, /每 5 分钟自动上传缓存/, 'release notes must describe the construction auto upload shutdown in Chinese')
assert.match(releaseNotes, /测试资料组/, 'release notes must describe the mock group fallback root cause in Chinese')
assert.match(releaseNotes, /00000000/, 'release notes must describe the construction 00000000 fix')
assert.match(releaseNotes, /version:\s*'V3\.0\.26'/, 'release notes must include V3.0.26')
assert.match(releaseNotes, /version:\s*'V3\.0\.25'/, 'release notes must include V3.0.25')
assert.match(releaseNotes, /version:\s*'V3\.0\.24'/, 'release notes must include V3.0.24')
assert.match(releaseNotes, /KPI 效率计时口径修正/, 'release notes must describe the KPI efficiency timing update in Chinese')
assert.match(releaseNotes, /在线时长融合 KPI/, 'release notes must describe the KPI online fusion update in Chinese')
assert.match(releaseNotes, /00000000/, 'release notes must keep the construction placeholder fix')
assert.doesNotMatch(releaseNotes, /TODO|TBD|placeholder/i, 'release notes must not contain placeholders')

const appLayout = read('v2-web/src/layouts/AppLayout.vue')
assert.match(appLayout, /releaseNotesVisible/, 'AppLayout must own the release notes dialog state')
assert.match(appLayout, /isAdmin/, 'AppLayout must gate the entry to administrators')
assert.match(appLayout, /v-if="isAdmin"/, 'release notes entry must be admin-only')
assert.match(appLayout, /更新内容|鏇存柊鍐呭/, 'AppLayout must render a Chinese update entry')
assert.match(appLayout, /<ElDialog[\s\S]*(更新内容|鏇存柊鍐呭)/, 'AppLayout must render the update dialog')

const loginView = read('v2-web/src/views/LoginView.vue')
assert.match(appLayout, /releaseNotesPageSize/, 'release notes dialog must define a small page size')
assert.match(appLayout, /pagedReleaseNotes/, 'release notes dialog must render paged release notes')
assert.match(appLayout, /<ElPagination/, 'release notes dialog must include pagination controls')
assert.match(loginView, /APP_VERSION/, 'LoginView must read the shared APP_VERSION')
assert.doesNotMatch(loginView, /V3\.0\.24/, 'LoginView must not hard-code the old version')

const webIndex = read('v2-web/index.html')
assert.match(webIndex, new RegExp(`Module Manager V${escapedVersion}`), `web HTML title must be ${EXPECTED_VERSION}`)

const staticVueIndex = read('v2-api/app/static/vue/index.html')
assert.match(staticVueIndex, new RegExp(`Module Manager V${escapedVersion}`), `built Vue static title must be ${EXPECTED_VERSION}`)

const staticVueAssetsDir = path.join(root, 'v2-api', 'app', 'static', 'vue', 'assets')
const staticVueScripts = fs.readdirSync(staticVueAssetsDir)
  .filter((name) => name.endsWith('.js'))
  .map((name) => fs.readFileSync(path.join(staticVueAssetsDir, name), 'utf8'))
  .join('\n')
assert.match(staticVueScripts, new RegExp(escapedVersion), `built Vue static assets must include ${EXPECTED_VERSION}`)

const legacyLayout = read('v2-web/src/components/AppLayout.vue')
assert.doesNotMatch(legacyLayout, /V3\.0\.24/, 'legacy layout must not show the old version')
assert.match(legacyLayout, new RegExp(`V${escapedVersion}`), 'legacy layout must show the new version')

const packageJson = JSON.parse(read('v2-web/package.json'))
assert.equal(packageJson.version, EXPECTED_VERSION, `web package version must be ${EXPECTED_VERSION}`)

const pyproject = read('v2-api/pyproject.toml')
assert.match(pyproject, new RegExp(`version = "${escapedVersion}"`), `API package version must be ${EXPECTED_VERSION}`)
assert.match(pyproject, new RegExp(`V${escapedVersion}`), `API description must mention V${EXPECTED_VERSION}`)

const mainPy = read('v2-api/app/main.py')
assert.match(mainPy, new RegExp(`version="${escapedVersion}"`), `FastAPI version must be ${EXPECTED_VERSION}`)

const opsStatus = read('v2-api/app/services/ops_status.py')
assert.match(opsStatus, new RegExp(`return "${escapedVersion}"`), `ops status version must be ${EXPECTED_VERSION}`)

console.log('admin release notes checks passed')
